---
- docker_container:
    name: samba-dc-bind
    image: "{{ samba_container_image['samba-dc' if not samba_dc_mitkrb5 | bool else 'samba-dc-mitkrb5'] }}"
    state: started
    restart_policy: always
    capabilities:
      - sys_admin
    network_mode: host
    env:
      CONTAINER_TYPE: "bind_dns"
    volumes:
      - /etc/bind:/etc/bind
      - /etc/sysconfig/network:/etc/sysconfig/network
      - /etc/sysconfig/bind:/etc/sysconfig/bind
      - /etc/samba:/etc/samba
      - /var/lib/samba:/var/lib/samba
      - /var/cache/samba:/var/cache/samba
      - /etc/resolv-container-samba-dc.conf:/etc/resolv.conf
    exposed_ports:
      - 53
      - 53/udp
